/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant_s;


import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;


/**
 *
 * @author Pardhu CooL
 */
public class Restaurants extends javax.swing.JFrame {

    
double firstnum;
double secondnum;
double result;
String operations;
double con;
double [] i = new double[5];


    /**
     * Creates new form Restaurants
     */

    public Restaurants() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jtxtDisplay = new javax.swing.JTextField();
        jEtn4 = new javax.swing.JButton();
        jButtonequalsto = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jEtn8 = new javax.swing.JButton();
        jEtn7 = new javax.swing.JButton();
        jEtn1 = new javax.swing.JButton();
        jEtn2 = new javax.swing.JButton();
        jButtonDot = new javax.swing.JButton();
        jEtn9 = new javax.swing.JButton();
        jEtn3 = new javax.swing.JButton();
        jButtonmulti = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jEtn5 = new javax.swing.JButton();
        jEtn6 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButtonaddsub = new javax.swing.JButton();
        jButtondiv = new javax.swing.JButton();
        jEtn0 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jEtnchicburg = new javax.swing.JCheckBox();
        jEtnchicsand = new javax.swing.JCheckBox();
        jEtncheburg = new javax.swing.JCheckBox();
        jtxtchicsand = new javax.swing.JTextField();
        jtxtchicburg = new javax.swing.JTextField();
        jtxtcheburg = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jEtnselect = new javax.swing.JComboBox<>();
        jEtntax = new javax.swing.JCheckBox();
        jEtnhomedel = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jEtntotal = new javax.swing.JButton();
        jEtnreceipt = new javax.swing.JButton();
        jEtnexit = new javax.swing.JButton();
        jreset = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        JEtn = new javax.swing.JTextField();
        jEtnconvert = new javax.swing.JButton();
        jEtnreset = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jEtncostofmeal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jEtncostdrinks = new javax.swing.JTextField();
        jtxtcostofmeal = new javax.swing.JTextField();
        jEtncostofdel = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jEtnsubtotal = new javax.swing.JLabel();
        jEtntax1 = new javax.swing.JLabel();
        jEtntot = new javax.swing.JLabel();
        jtxtsubtotal = new javax.swing.JTextField();
        jtxttax = new javax.swing.JTextField();
        jtxttotal = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1370, 700));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Receipt", jPanel8);

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDisplay.setToolTipText("");
        jtxtDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jEtn4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEtn4.setText("4");
        jEtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtn4ActionPerformed(evt);
            }
        });

        jButtonequalsto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonequalsto.setText("=");
        jButtonequalsto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonequalstoActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jEtn8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEtn8.setText("8");
        jEtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtn8ActionPerformed(evt);
            }
        });

        jEtn7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEtn7.setText("7");
        jEtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtn7ActionPerformed(evt);
            }
        });

        jEtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEtn1.setText("1");
        jEtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtn1ActionPerformed(evt);
            }
        });

        jEtn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEtn2.setText("2");
        jEtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtn2ActionPerformed(evt);
            }
        });

        jButtonDot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDot.setText(".");
        jButtonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDotActionPerformed(evt);
            }
        });

        jEtn9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEtn9.setText("9");
        jEtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtn9ActionPerformed(evt);
            }
        });

        jEtn3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEtn3.setText("3");
        jEtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtn3ActionPerformed(evt);
            }
        });

        jButtonmulti.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonmulti.setText("*");
        jButtonmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmultiActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton14.setText("-");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jEtn5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEtn5.setText("5");
        jEtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtn5ActionPerformed(evt);
            }
        });

        jEtn6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEtn6.setText("6");
        jEtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtn6ActionPerformed(evt);
            }
        });

        jButton19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton19.setText("C");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButtonaddsub.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonaddsub.setText("+/-");
        jButtonaddsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddsubActionPerformed(evt);
            }
        });

        jButtondiv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtondiv.setText("/");
        jButtondiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondivActionPerformed(evt);
            }
        });

        jEtn0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEtn0.setText("0");
        jEtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtn0ActionPerformed(evt);
            }
        });

        jButton23.setFont(new java.awt.Font("Wingdings", 1, 18)); // NOI18N
        jButton23.setText("<-");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonaddsub, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jEtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jEtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jEtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jEtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jEtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jEtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jEtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDot, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jEtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jEtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jEtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonmulti, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtondiv, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonequalsto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jtxtDisplay))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonaddsub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jEtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jEtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(jEtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jEtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jEtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jEtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDot, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jEtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jEtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jEtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonmulti, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtondiv, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonequalsto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Calculator", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jEtnchicburg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEtnchicburg.setText("Chicken Burger");
        jEtnchicburg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEtnchicburgMouseClicked(evt);
            }
        });
        jEtnchicburg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtnchicburgActionPerformed(evt);
            }
        });

        jEtnchicsand.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEtnchicsand.setText("Chicken Sandwich");
        jEtnchicsand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEtnchicsandMouseClicked(evt);
            }
        });

        jEtncheburg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEtncheburg.setText("Cheese Burger");
        jEtncheburg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEtncheburgMouseClicked(evt);
            }
        });
        jEtncheburg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtncheburgActionPerformed(evt);
            }
        });

        jtxtchicsand.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtchicsand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtchicburg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtchicburg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtchicburg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtchicburgActionPerformed(evt);
            }
        });

        jtxtcheburg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtcheburg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Drinks");

        jEtnselect.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEtnselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Drink", "Thums Up", "Mountain Dew", "Pepsi", "Ice Tea", "Sprite" }));
        jEtnselect.setBorder(null);
        jEtnselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtnselectActionPerformed(evt);
            }
        });

        jEtntax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEtntax.setText("Tax");
        jEtntax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEtntaxMouseClicked(evt);
            }
        });
        jEtntax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtntaxActionPerformed(evt);
            }
        });

        jEtnhomedel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEtnhomedel.setText("Home Delivery");
        jEtnhomedel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEtnhomedelMouseClicked(evt);
            }
        });
        jEtnhomedel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtnhomedelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEtncheburg)
                            .addComponent(jEtnchicsand)
                            .addComponent(jLabel1)
                            .addComponent(jEtntax)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jEtnchicburg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtchicsand)
                    .addComponent(jtxtchicburg)
                    .addComponent(jEtnhomedel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEtnselect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtcheburg))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jEtnchicburg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jEtnchicsand, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEtncheburg)
                            .addComponent(jtxtcheburg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtxtchicburg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtchicsand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jEtnselect, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEtntax)
                    .addComponent(jEtnhomedel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jEtntotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jEtntotal.setText("Total");
        jEtntotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEtntotalMouseClicked(evt);
            }
        });
        jEtntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtntotalActionPerformed(evt);
            }
        });

        jEtnreceipt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jEtnreceipt.setText("Receipt");
        jEtnreceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEtnreceiptMouseClicked(evt);
            }
        });
        jEtnreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtnreceiptActionPerformed(evt);
            }
        });

        jEtnexit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jEtnexit.setText("Exit");
        jEtnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtnexitActionPerformed(evt);
            }
        });

        jreset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jreset.setText("Reset");
        jreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jresetActionPerformed(evt);
            }
        });

        jToggleButton1.setBackground(new java.awt.Color(255, 51, 0));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton1.setText("Go");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jEtntotal)
                .addGap(18, 18, 18)
                .addComponent(jEtnreceipt)
                .addGap(18, 18, 18)
                .addComponent(jreset)
                .addGap(66, 66, 66)
                .addComponent(jEtnexit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jEtnreceipt)
                        .addComponent(jEtntotal))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jEtnexit)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One..", "USA", "England", "Australia", "Kenya", " ", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        JEtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JEtn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JEtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        JEtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEtnActionPerformed(evt);
            }
        });

        jEtnconvert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEtnconvert.setText("Convert");
        jEtnconvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtnconvertActionPerformed(evt);
            }
        });

        jEtnreset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEtnreset.setText("Close");
        jEtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jEtnconvert)
                .addGap(27, 27, 27)
                .addComponent(jEtnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JEtn, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, 158, Short.MAX_VALUE)
                    .addComponent(jTextField5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JEtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jEtnconvert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEtnreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Cost Of Drinks");

        jEtncostofmeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jEtncostofmeal.setText("Cost Of Meal");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cost Of Delivery");

        jEtncostdrinks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEtncostdrinks.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jEtncostdrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtcostofmeal.setEditable(false);
        jtxtcostofmeal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtcostofmeal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtcostofmeal.setText("0");
        jtxtcostofmeal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtcostofmeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcostofmealActionPerformed(evt);
            }
        });

        jEtncostofdel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jEtncostofdel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jEtncostofdel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jEtncostofdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEtncostofdelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEtncostofmeal)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEtncostofdel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtcostofmeal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEtncostdrinks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jEtncostdrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtcostofmeal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEtncostofmeal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEtncostofdel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jEtnsubtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jEtnsubtotal.setText("SubTotal :");
        jEtnsubtotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEtnsubtotalMouseClicked(evt);
            }
        });

        jEtntax1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jEtntax1.setText("Tax :");

        jEtntot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jEtntot.setText("TotaL :");

        jtxtsubtotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtsubtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsubtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtsubtotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtsubtotalMouseClicked(evt);
            }
        });
        jtxtsubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtsubtotalActionPerformed(evt);
            }
        });

        jtxttax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxttax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxttax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxttotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxttotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxttotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jEtnsubtotal)
                        .addGap(30, 30, 30)
                        .addComponent(jtxtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEtntax1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEtntot, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxttax)
                            .addComponent(jtxttotal))))
                .addGap(54, 54, 54))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jEtnsubtotal))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtxtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEtntax1)
                    .addComponent(jtxttax, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jEtntot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxttotal))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField1.setText("Restaurant Management Systems");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(636, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(746, 746, 746))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jEtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtn7ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jEtn7.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jEtn7ActionPerformed

    private void jEtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtn8ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jEtn8.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jEtn8ActionPerformed

    private void jEtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtn9ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jEtn9.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jEtn9ActionPerformed

    private void jEtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtn4ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jEtn4.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jEtn4ActionPerformed

    private void jEtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtn5ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jEtn5.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jEtn5ActionPerformed

    private void jEtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtn6ActionPerformed
         String Enternumber = jtxtDisplay.getText() + jEtn6.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jEtn6ActionPerformed

    private void jEtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtn1ActionPerformed
         String Enternumber = jtxtDisplay.getText() + jEtn1.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jEtn1ActionPerformed

    private void jEtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtn2ActionPerformed
         String Enternumber = jtxtDisplay.getText() + jEtn2.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jEtn2ActionPerformed

    private void jEtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtn3ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jEtn3.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jEtn3ActionPerformed

    private void jEtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtn0ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jEtn0.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jEtn0ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        jtxtDisplay.setText(null);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
       String backspace= null;
       
            if(jtxtDisplay.getText().length() > 0)
            {
                StringBuilder strB = new StringBuilder(jtxtDisplay.getText());
                strB.deleteCharAt(jtxtDisplay.getText().length()-1);
                backspace =strB.toString();
                jtxtDisplay.setText(backspace);             
    }//GEN-LAST:event_jButton23ActionPerformed
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations="+";        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDotActionPerformed
        jtxtDisplay.setText(jtxtDisplay.getText() + jButtonDot.getText());
    }//GEN-LAST:event_jButtonDotActionPerformed

    private void jButtondivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondivActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations="/";
    }//GEN-LAST:event_jButtondivActionPerformed

    private void jButtonmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmultiActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations="*";
    }//GEN-LAST:event_jButtonmultiActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
       firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations="-";
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButtonaddsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddsubActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops*=(-1);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButtonaddsubActionPerformed

    private void jButtonequalstoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonequalstoActionPerformed
        String answer;
        secondnum=Double.parseDouble(jtxtDisplay.getText());
        if(operations == "+"){
            result = firstnum + secondnum;
            answer = String.format("%.2f",result);
            jtxtDisplay.setText(answer);
        }
            else  if (operations == "-"){
             result = firstnum - secondnum;
            answer = String.format("%.2f",result);
            jtxtDisplay.setText(answer);  
            } 
            else  if(operations == "*"){
            result = firstnum * secondnum;
            answer = String.format("%.2f",result);
            jtxtDisplay.setText(answer);
            }
            else  if(operations == "/"){
            result = firstnum / secondnum;
            answer = String.format("%.2f",result);
            jtxtDisplay.setText(answer);
            }
            
    }//GEN-LAST:event_jButtonequalstoActionPerformed
/*
    private void jtxtcostofmealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcostofmealActionPerformed
        double chicburger = Double.parseDouble(jtxtchicburg.getText());
        double ichicburger = 2.39;
        
        if( jEtnchicburg.isSelected() )
        {
            i[0] = (chicburger * ichicburger);    
            String pmeal = String.format("%.2f", i[0]);
            jtxtcostofmeal.setText(pmeal );
        }
    }//GEN-LAST:event_jtxtcostofmealActionPerformed
*/
    private void JEtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEtnActionPerformed
       
        
       
        
        
    }//GEN-LAST:event_JEtnActionPerformed

    private void jEtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtnresetActionPerformed
       JEtn.setText(null);
       jTextField5.setText(null);
       jComboBox2.setSelectedIndex(0);
    }//GEN-LAST:event_jEtnresetActionPerformed

    private void jEtnconvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtnconvertActionPerformed
        double British_Pound;
        British_Pound = Double.parseDouble(jTextField5.getText());
        if(jComboBox2.getSelectedItem() == "Australia" ){
        String cConvert1 = String.format("NIG % .2f",British_Pound * 15.66);
        JEtn.setText(cConvert1);
        }
        if(jComboBox2.getSelectedItem() == "Kenya" ){
        String cConvert2 = String.format("KEN % .2f",British_Pound * 55.6);
        JEtn.setText(cConvert2);
        }
        if(jComboBox2.getSelectedItem() == "England" ){
        String cConvert3 = String.format("ENG % .2f",British_Pound * 12.2);
        JEtn.setText(cConvert3);
        }
        if(jComboBox2.getSelectedItem() == "USA" ){
        String cConvert4 = String.format("$ % .2f",British_Pound * 100.06);
        JEtn.setText(cConvert4);
        }
    }//GEN-LAST:event_jEtnconvertActionPerformed
/*
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        
            
    }//GEN-LAST:event_jComboBox2ActionPerformed
*/
    private void jEtnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jEtnexitActionPerformed

    private void jEtnselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtnselectActionPerformed
        double sprite=20;
        double thumsup=40;
        double mdew=35;
        double pepsi=25;
        double icetea=30 ;
        if(jEtnselect.getSelectedItem() == "Sprite" ){
        String cspr = String.format("%.2f",sprite);
        jEtncostdrinks.setText(cspr);
        }
        if(jEtnselect.getSelectedItem() == "Thums Up" ){
        String ctup = String.format("%.2f",thumsup);
        jEtncostdrinks.setText(ctup);
        }
        if(jEtnselect.getSelectedItem() == "Mountain Dew" ){
        String cmd = String.format("%.2f",mdew);
        jEtncostdrinks.setText(cmd);
        }
        if(jEtnselect.getSelectedItem() == "Ice Tea" ){
        String cit = String.format("%.2f",icetea);
        jEtncostdrinks.setText(cit);
        }
        if(jEtnselect.getSelectedItem() == "Pepsi" ){
        String cpep = String.format("%.2f",pepsi);
        jEtncostdrinks.setText(cpep);
        }
        if(jEtnselect.getSelectedItem() == "Select a Drink" ){
       
        jEtncostdrinks.setText(null);
        }
        
    }//GEN-LAST:event_jEtnselectActionPerformed

    private void jtxtchicburgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtchicburgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtchicburgActionPerformed

    private void jEtnhomedelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtnhomedelActionPerformed
        
    }//GEN-LAST:event_jEtnhomedelActionPerformed

    private void jEtnhomedelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEtnhomedelMouseClicked
        double idelivery = 3.39;
        
        if(jEtnhomedel.isSelected()){
            String pdelivery = String.format("%.2f",idelivery);
            jEtncostofdel.setText(pdelivery);
        }
        else
        {
            jEtncostofdel.setText(null);
        }
    }//GEN-LAST:event_jEtnhomedelMouseClicked

    private void jEtncostofdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtncostofdelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEtncostofdelActionPerformed

    private void jEtnreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtnreceiptActionPerformed
              
        double qty1 = Double.parseDouble(jtxtchicburg.getText());
        double qty2 = Double.parseDouble(jtxtchicsand.getText());
        double qty3 = Double.parseDouble(jtxtcheburg.getText());
        
        jTextArea1.append("Restaurant Management System:\n\n" + "\nChicken Burger:\t\t" + qty1 + "\nChicken Sandwich:\t\t" + qty2 +  "\nCheese Burger:\t\t" + qty3 + "\n\n Thanks For Coming.." + "\\nVisit Again");
                    
        
    }//GEN-LAST:event_jEtnreceiptActionPerformed

    private void jEtnreceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEtnreceiptMouseClicked
        //jEtncostofdel.setText(null);
        
        
        jEtncostdrinks.setText(null);
        jtxtcostofmeal.setText(null);
        jEtncostofdel.setText(null);
        jtxtsubtotal.setText(null);
        jtxttax.setText(null);
        jtxttotal.setText(null);
        jtxtchicburg.setText(null);
        jtxtchicsand.setText(null);
        jtxtcheburg.setText(null);
       
       

    
    }//GEN-LAST:event_jEtnreceiptMouseClicked

    private void jEtnchicburgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtnchicburgActionPerformed
        
    }//GEN-LAST:event_jEtnchicburgActionPerformed

    private void jEtnchicburgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEtnchicburgMouseClicked
        double cmeal = Double.parseDouble(jtxtcostofmeal.getText());
        double chicburger = Double.parseDouble(jtxtchicburg.getText());
        double ichicburger = 125;
        
        if( jEtnchicburg.isSelected() )
        {
            i[0] = (chicburger * ichicburger)+ cmeal ;    
            String pmeal = String.format("%.2f", i[0]);
            jtxtcostofmeal.setText(pmeal);
        }
    }//GEN-LAST:event_jEtnchicburgMouseClicked

    private void jEtnchicsandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEtnchicsandMouseClicked
        double cmeal = Double.parseDouble(jtxtcostofmeal.getText());
        double chicsand = Double.parseDouble(jtxtchicsand.getText());
        double ichicsand = 130;
        
        if(jEtnchicsand.isSelected())
        {
            i[1] = (chicsand * ichicsand) + cmeal;
            String pMeal = String.format("%.2f", i[1]);
            jtxtcostofmeal.setText(pMeal);
        }
    }//GEN-LAST:event_jEtnchicsandMouseClicked

    private void jEtncheburgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEtncheburgMouseClicked
       double cmeal = Double.parseDouble(jtxtcostofmeal.getText());
        double cheburg = Double.parseDouble(jtxtcheburg.getText());
        double icheburg = 200;
        
        if(jEtncheburg.isSelected())
        {
            i[2] = (cheburg * icheburg) + cmeal;
            String pMeal = String.format("%.2f", i[2]);
            jtxtcostofmeal.setText(pMeal);
        }
    }//GEN-LAST:event_jEtncheburgMouseClicked

    private void jEtncheburgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtncheburgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEtncheburgActionPerformed
/*
    private void jEtntaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtntaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEtntaxActionPerformed
*/
    private void jEtntaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEtntaxMouseClicked
        double itax = 18;
        
        if(jEtntax.isSelected()){
            String ptax = String.format("%.2f",itax);
            jtxttax.setText(ptax);
        }
        else
        {
            jEtntax1.setText(null);
        }
        
        
      
        double ctotal1 = Double.parseDouble(jEtncostdrinks.getText());
        double ctotal2 = Double.parseDouble(jEtncostofdel.getText());
        double ctotal3 = Double.parseDouble(jtxtcostofmeal.getText());
        
        double alltotal = (ctotal1 + ctotal2 + ctotal3)/100;
        String itotal =String.format("%.2f",alltotal);
        jtxttax.setText(itotal);
       
    }//GEN-LAST:event_jEtntaxMouseClicked

    private void jEtntotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEtntotalMouseClicked
        double ctotal1 = Double.parseDouble(jEtncostdrinks.getText());
        double ctotal2 = Double.parseDouble(jEtncostofdel.getText());
        double ctotal3 = Double.parseDouble(jtxtcostofmeal.getText());
        double ctotal4 = Double.parseDouble(jtxttax.getText());
        
        
        double alltotal = ctotal1 + ctotal2 + ctotal3 + ctotal4;
        String itotal =String.format("%.2f",alltotal);
        jtxttotal.setText(itotal);
        double subtotal = ctotal1 + ctotal2 + ctotal3 ;
        String subtot =String.format("%.2f",subtotal);
        jtxtsubtotal.setText(subtot);
        
        String itaxtotal =String.format("%.2f",ctotal4);
        jtxttax.setText(itaxtotal);

    }//GEN-LAST:event_jEtntotalMouseClicked
/*
    private void jEtntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEtntotalActionPerformed
       
    }//GEN-LAST:event_jEtntotalActionPerformed

    private void jtxtsubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtsubtotalActionPerformed
        
    }//GEN-LAST:event_jtxtsubtotalActionPerformed
*/
    private void jtxtsubtotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtsubtotalMouseClicked
     
    }//GEN-LAST:event_jtxtsubtotalMouseClicked

    private void jEtnsubtotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEtnsubtotalMouseClicked
        double ctotal1 = Double.parseDouble(jEtncostdrinks.getText());
        double ctotal2 = Double.parseDouble(jEtncostofdel.getText());
        double ctotal3 = Double.parseDouble(jtxtcostofmeal.getText());
        
        double alltotal = ctotal1 + ctotal2 + ctotal3;
        String itotal =String.format("%.2f",alltotal);
        jtxtsubtotal.setText(itotal);
    }//GEN-LAST:event_jEtnsubtotalMouseClicked

    private void jresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jresetActionPerformed
        jEtncostdrinks.setText("0");
        jtxtcostofmeal.setText("0");
        jEtncostofdel.setText("0");
        
        jtxttax.setText("0");
        jtxttotal.setText("0");
        jtxtchicburg.setText("0");
        jtxtchicsand.setText("0");
        jtxtcheburg.setText("0");
        jtxttotal.setText("0");
        jtxtsubtotal.setText("0");
    }//GEN-LAST:event_jresetActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
       
        String a6 = "NA";
        Object selectedItem = jEtnselect.getSelectedItem();
if (selectedItem != null)
{
    String selectedItemStr = selectedItem.toString();
    a6=(selectedItemStr); 
}
double a =0.00;
if(jEtnhomedel.isSelected())
    a=3.39;
try{
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/rest","root","")) {
                String sql = "insert into rest values(?,?,?,?,?,?,?)";
                PreparedStatement p = cn.prepareStatement(sql);
                p.setInt(1, Integer.parseInt(jtxtchicburg.getText()));
                p.setInt(2,Integer.parseInt(jtxtchicsand.getText()));
                p.setInt(3,Integer.parseInt(jtxtcheburg.getText()));
                p.setDouble(4,Double.parseDouble(jtxttax.getText()));
                p.setDouble(5,a);
                p.setDouble(6, Double.parseDouble(jtxttotal.getText()));
                p.setString(7,a6);
                p.executeUpdate();
            }
            JOptionPane.showMessageDialog(null,"Inserted!!!");
        }
        catch(HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e){
        JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JEtn;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JButton jButtonaddsub;
    private javax.swing.JButton jButtondiv;
    private javax.swing.JButton jButtonequalsto;
    private javax.swing.JButton jButtonmulti;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JButton jEtn0;
    private javax.swing.JButton jEtn1;
    private javax.swing.JButton jEtn2;
    private javax.swing.JButton jEtn3;
    private javax.swing.JButton jEtn4;
    private javax.swing.JButton jEtn5;
    private javax.swing.JButton jEtn6;
    private javax.swing.JButton jEtn7;
    private javax.swing.JButton jEtn8;
    private javax.swing.JButton jEtn9;
    private javax.swing.JCheckBox jEtncheburg;
    private javax.swing.JCheckBox jEtnchicburg;
    private javax.swing.JCheckBox jEtnchicsand;
    private javax.swing.JButton jEtnconvert;
    private javax.swing.JTextField jEtncostdrinks;
    private javax.swing.JTextField jEtncostofdel;
    private javax.swing.JLabel jEtncostofmeal;
    private javax.swing.JButton jEtnexit;
    private javax.swing.JCheckBox jEtnhomedel;
    private javax.swing.JButton jEtnreceipt;
    private javax.swing.JButton jEtnreset;
    private javax.swing.JComboBox<String> jEtnselect;
    private javax.swing.JLabel jEtnsubtotal;
    private javax.swing.JCheckBox jEtntax;
    private javax.swing.JLabel jEtntax1;
    private javax.swing.JLabel jEtntot;
    private javax.swing.JButton jEtntotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton jreset;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtcheburg;
    private javax.swing.JTextField jtxtchicburg;
    private javax.swing.JTextField jtxtchicsand;
    private javax.swing.JTextField jtxtcostofmeal;
    private javax.swing.JTextField jtxtsubtotal;
    private javax.swing.JTextField jtxttax;
    private javax.swing.JTextField jtxttotal;
    // End of variables declaration//GEN-END:variables

}